name: 部署静态内容到 GitHub Pages

on:
  push:
    branches: ["main", "develop", "feature/*", "R1"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Pages
        uses: actions/configure-pages@v5
      
      - name: 准备部署内容
        run: |
          mkdir -p _site
          if [ "${{ github.ref_name }}" = "main" ]; then
            cp -r * _site/ || true
          else
            mkdir -p _site/${{ github.ref_name }}
            cp -r * _site/${{ github.ref_name }}/ || true
          fi
      
      - name: 上传内容
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
