name: Deploy to Pages Repository

on:
  push:
    branches:
      - main
      - 'R*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      
      - name: Create temporary directory for deployment
        run: |
          mkdir deploy_temp
          if [ -f .deployignore ]; then
            rsync -av --exclude-from=.deployignore . deploy_temp/
          else
            rsync -av . deploy_temp/
          fi
      
      - name: Deploy to Pages Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          external_repository: tobenot/beyond-books-pages
          publish_branch: main
          publish_dir: ./deploy_temp
          destination_dir: ${{ steps.branch-name.outputs.BRANCH_NAME }}
          
      - name: Update Index Page
        run: |
          git clone https://tobenot:${{ secrets.PAGES_DEPLOY_TOKEN }}@github.com/tobenot/beyond-books-pages.git temp_pages
          cd temp_pages
          echo "# Beyond Books 索引页面" > index.md
          echo "" >> index.md
          echo "## 可用分支:" >> index.md
          for dir in */; do
            branch=${dir%/}
            echo "- [$branch]($branch/)" >> index.md
          done
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.md
          git commit -m "更新索引页面"
          git push
          cd ..
          rm -rf temp_pages