name: Deploy Static Content to GitHub Pages

on:
  push:
    branches: ["main", "develop", "feature/*", "R*"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Prepare Deployment Content
        run: |
          # 保存当前分支名称
          current_branch="${{ github.ref_name }}"
          
          # 创建临时目录
          mkdir -p _temp_site
          
          # 复制所有分支内容
          git for-each-ref --format='%(refname:short)' refs/heads | while read branch; do
            git checkout $branch
            if [ "$branch" = "main" ]; then
              mkdir -p _temp_site/main
              cp -r * _temp_site/main/ 2>/dev/null || true
            else
              mkdir -p _temp_site/$branch
              cp -r * _temp_site/$branch/ 2>/dev/null || true
            fi
          done
          
          # 确保当前分支内容是最新的
          git checkout $current_branch
          if [ "$current_branch" = "main" ]; then
            rm -rf _temp_site/main
            mkdir -p _temp_site/main
            cp -r * _temp_site/main/ 2>/dev/null || true
          else
            rm -rf _temp_site/$current_branch
            mkdir -p _temp_site/$current_branch
            cp -r * _temp_site/$current_branch/ 2>/dev/null || true
          fi
          
          # 创建索引页面
          echo "<html><body><h1>分支列表</h1><ul>" > _temp_site/index.html
          for dir in _temp_site/*/; do
            branch=$(basename "$dir")
            echo "<li><a href='/$branch'>$branch</a></li>" >> _temp_site/index.html
          done
          echo "</ul></body></html>" >> _temp_site/index.html
          
          # 移动临时目录到最终位置
          rm -rf _site
          mv _temp_site _site
      
      - name: List deployment content
        run: ls -R _site
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4